NIFTY_STOCKS = [
    {"symbol": "RELIANCE.NS", "company_name": "Reliance Industries"},
    {"symbol": "TCS.NS", "company_name": "Tata Consultancy Services"},
    {"symbol": "HDFCBANK.NS", "company_name": "HDFC Bank"},
    {"symbol": "INFY.NS", "company_name": "Infosys"},
    {"symbol": "ICICIBANK.NS", "company_name": "ICICI Bank"},
    {"symbol": "HINDUNILVR.NS", "company_name": "Hindustan Unilever"},
    {"symbol": "BHARTIARTL.NS", "company_name": "Bharti Airtel"},
    {"symbol": "ITC.NS", "company_name": "ITC Limited"},
    {"symbol": "LT.NS", "company_name": "Larsen & Toubro"},
    {"symbol": "SBIN.NS", "company_name": "State Bank of India"},
    {"symbol": "ADANIENT.NS", "company_name": "Adani Enterprises"},
    {"symbol": "ASIANPAINT.NS", "company_name": "Asian Paints"},
    {"symbol": "AXISBANK.NS", "company_name": "Axis Bank"},
    {"symbol": "BAJAJ-AUTO.NS", "company_name": "Bajaj Auto"},
    {"symbol": "BAJFINANCE.NS", "company_name": "Bajaj Finance"},
    {"symbol": "BAJAJFINSV.NS", "company_name": "Bajaj Finserv"},
    {"symbol": "BPCL.NS", "company_name": "Bharat Petroleum"},
    {"symbol": "BRITANNIA.NS", "company_name": "Britannia"},
    {"symbol": "CIPLA.NS", "company_name": "Cipla"},
    {"symbol": "COALINDIA.NS", "company_name": "Coal India"},
    {"symbol": "DRREDDY.NS", "company_name": "Dr. Reddy's Laboratories"},
    {"symbol": "EICHERMOT.NS", "company_name": "Eicher Motors"},
    {"symbol": "GRASIM.NS", "company_name": "Grasim Industries"},
    {"symbol": "HEROMOTOCO.NS", "company_name": "Hero MotoCorp"},
    {"symbol": "HINDALCO.NS", "company_name": "Hindalco"},
    {"symbol": "HDFC.NS", "company_name": "HDFC"},
    {"symbol": "INDUSINDBK.NS", "company_name": "IndusInd Bank"},
    {"symbol": "KOTAKBANK.NS", "company_name": "Kotak Mahindra Bank"},
    {"symbol": "M&M.NS", "company_name": "Mahindra & Mahindra"},
    {"symbol": "MARUTI.NS", "company_name": "Maruti Suzuki"},
    {"symbol": "NESTLEIND.NS", "company_name": "Nestle India"},
    {"symbol": "NTPC.NS", "company_name": "NTPC"},
    {"symbol": "ONGC.NS", "company_name": "ONGC"},
    {"symbol": "POWERGRID.NS", "company_name": "Power Grid Corp"},
    {"symbol": "SBILIFE.NS", "company_name": "SBI Life Insurance"},
    {"symbol": "SHREECEM.NS", "company_name": "Shree Cement"},
    {"symbol": "SUNPHARMA.NS", "company_name": "Sun Pharma"},
    {"symbol": "TATACONSUM.NS", "company_name": "Tata Consumer"},
    {"symbol": "TATAMOTORS.NS", "company_name": "Tata Motors"},
    {"symbol": "TATASTEEL.NS", "company_name": "Tata Steel"},
    {"symbol": "TECHM.NS", "company_name": "Tech Mahindra"},
    {"symbol": "TITAN.NS", "company_name": "Titan"},
    {"symbol": "ULTRACEMCO.NS", "company_name": "UltraTech Cement"},
    {"symbol": "UPL.NS", "company_name": "UPL"},
    {"symbol": "WIPRO.NS", "company_name": "Wipro"}
]
